spring.application.name=Expenses-Application

server.port=8080

# データベース接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/newschema
spring.datasource.username=app
spring.datasource.password=AppStrongPass_1234!


# 例外設定
#Spring Boot 3.2系以降では spring.mvc.throw-exception-if-no-handler-found は deprecated 扱い。
#Framework 6.1 以降で DispatcherServlet が基本的に NoHandlerFoundException を投げる
#spring.mvc.throw-exception-if-no-handler-found=true # 404を例外として扱う（NoHandlerFoundExceptionを発生させる）

#spring.web.resources.add-mappings=false

logging.level.root=info

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**/*.xml
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

mybatis.type-aliases-package=com.example.expenses.dto.request,com.example.expenses.dto.response,com.example.expenses.domain

logging.level.org.mybatis=DEBUG

#mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl
logging.level.org.apache.ibatis=DEBUG

logging.level.org.springframework.security=DEBUG

# フォルダ
#実行方法	./ の指す場所
#IDE（Eclipse）	プロジェクトルート
#java -jar app.jar（その場で実行）	コマンド実行したディレクトリ
file.upload-dir=./uploads
batch.report.output-dir=./report-output
file.input-dir=./input

# Mail Config
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttles.enable=false
app.mail.from=no-reply@example.local
batch.notification.admin-email=admin@example.local


# batch config
#実行するJobの名前を指定
spring.batch.job.name=csvImportJob
spring.batch.initialize.schema= always
#アプリ起動時ＪＯＢを自動実行設定
spring.batch.job.enabled=false
#スケジュール設定（毎月1日に実行）秒 分 時 日 月 曜日の順に指定
batch.schedule.monthly-report=0 0 0 1 * * 

# File Upload Config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

# 開発ツールの自動再起動を無効化
spring.devtools.restart.enabled=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379